export type GallerySlide = { image: string; title: string; description: string };

const gallery = (slug: string, items: Array<[string, string]>): GallerySlide[] => items.map(([title, description], index) => ({
  image: `/images/departments/gallery/${slug}/${String(index + 1).padStart(2, "0")}.jpg`, title, description,
}));

export const departmentGalleries: Record<string, GallerySlide[]> = {
  Beni: gallery("beni", [["Llanos de Moxos", "Sabanas, humedales y horizonte amazónico."], ["Trinidad", "Capital beniana y centro de la cultura mojeña."], ["Laguna Suárez", "Agua, vegetación tropical y descanso cerca de Trinidad."], ["Rurrenabaque", "Puerta de entrada a la Amazonía boliviana."], ["Sabanas del Beni", "Paisaje vivo modelado por los ciclos del agua."]]),
  Chuquisaca: gallery("chuquisaca", [["Sucre", "Arquitectura blanca y patrimonio histórico."], ["Maragua", "Paisaje geológico de formas monumentales."], ["Tarabuco", "Mercado, textiles y memoria Yampara."], ["Valle de Cinti", "Viñedos patrimoniales y cepas criollas."], ["La Glorieta", "Arquitectura singular en las cercanías de Sucre."]]),
  Cochabamba: gallery("cochabamba", [["Valle de Cochabamba", "Ciudad-jardín en el corazón de los valles."], ["Cristo de la Concordia", "Mirador emblemático sobre la ciudad."], ["Tunari", "La gran montaña que define el horizonte valluno."], ["Incallajta", "Complejo arqueológico incaico entre montañas."], ["Torotoro", "Cañones, roca y paisajes prehistóricos."]]),
  "La Paz": gallery("la-paz", [["La Paz e Illimani", "Una ciudad vertical bajo la cordillera Real."], ["Valle de la Luna", "Formaciones de arcilla esculpidas por la erosión."], ["Tiwanaku", "Centro monumental de una civilización andina."], ["Lago Titicaca", "Agua sagrada y paisaje de altura."], ["Yungas", "Transición exuberante entre Andes y Amazonía."]]),
  Oruro: gallery("oruro", [["Sajama", "El nevado más alto de Bolivia."], ["Ciudad de Oruro", "Historia minera y corazón del altiplano."], ["Carnaval de Oruro", "Patrimonio vivo, música y danza."], ["Salar de Coipasa", "Horizonte mineral en el occidente boliviano."], ["Termas de Sajama", "Aguas termales frente a volcanes andinos."]]),
  Pando: gallery("pando", [["Cobija", "Capital amazónica a orillas del río Acre."], ["Bosque pandino", "Selva húmeda de extraordinaria biodiversidad."], ["Río Tahuamanu", "Sistema fluvial que articula el territorio."], ["Amazonía boliviana", "Dosel verde, ríos y vida silvestre."], ["Manuripi", "Reserva amazónica y territorio de la castaña."]]),
  Potosí: gallery("potosi", [["Cerro Rico", "Montaña inseparable de la historia de Potosí."], ["Salar de Uyuni", "La mayor planicie de sal del mundo."], ["Villa Imperial", "Calles, templos y memoria colonial."], ["Laguna Colorada", "Agua rojiza, flamencos y volcanes."], ["Reserva Eduardo Avaroa", "Desiertos, géiseres y lagunas altoandinas."]]),
  "Santa Cruz": gallery("santa-cruz", [["Santa Cruz de la Sierra", "Plaza, clima tropical y vida camba."], ["Parque Amboró", "Encuentro de Andes, Amazonía y Chaco."], ["Samaipata", "Valles, bosque y patrimonio arqueológico."], ["Misiones de Chiquitos", "Arquitectura, música y tradición misional."], ["Noel Kempff Mercado", "Mesetas, cascadas y selva remota."]]),
  Tarija: gallery("tarija", [["Tarija", "Ciudad de plazas, jardines y tradición chapaca."], ["Valle de la Concepción", "Paisaje central de los vinos de altura."], ["Casa Dorada", "Arquitectura republicana en el centro histórico."], ["San Jacinto", "Lago y serranías muy cerca de la ciudad."], ["Cordillera de Sama", "Lagunas, puna y grandes horizontes."]]),
};
