export type Wine = {
  id: string;
  name: string;
  winery: string;
  valley: "Valle de Cinti" | "Valle Central de Tarija";
  department: "Chuquisaca" | "Tarija";
  grapes: string[];
  style: "Blanco" | "Rosado" | "Tinto" | "Naranjo" | "Espumante";
  appearance: string;
  nose: string[];
  palate: string[];
  character: string[];
  process?: string;
  vintage?: string;
  zone?: string;
  altitude?: string;
  fermentation?: string;
  malolactic?: string;
  aging?: string;
  agingVessel?: string;
  agingTime?: string;
  alcohol?: string;
  aromaFamilies?: Partial<Record<"Frutal" | "Floral" | "Herbal / vegetal" | "Especiado" | "Crianza", string[]>>;
  palateAxes?: Partial<Record<"Dulzor" | "Acidez" | "Alcohol" | "Taninos" | "Astringencia" | "Cuerpo" | "Intensidad" | "Textura" | "Persistencia", string>>;
};

export const wines: Wine[] = [
  { id: "jardin-lumen-blanc-noir", name: "Finca Lumen Blanc de Noir", winery: "Jardín Oculto", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Vischoqueña"], style: "Blanco", appearance: "Blanco brillante", nose: ["Fruta fresca", "Carácter varietal delicado"], palate: ["Jugoso", "Fresco", "Flexible", "Ligero"], character: ["Fino", "Delicado", "Cuerpo ligero"] },
  { id: "jardin-san-roque-rose", name: "San Roque Rosé", winery: "Jardín Oculto", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Blend de criollas"], style: "Rosado", appearance: "Rosa pálido", nose: ["Uva fresca", "Fruta roja delicada"], palate: ["Frutal", "Flexible", "Buen volumen"], character: ["Fresco", "Redondo", "Amable"] },
  { id: "jardin-molle-pampa", name: "Molle Pampa Negra Criolla", winery: "Jardín Oculto", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Negra Criolla"], style: "Tinto", appearance: "Rojo pálido", nose: ["Especias finas", "Piel de naranja", "Notas herbales-amargas"], palate: ["Profundo", "Texturado", "Complejo"], character: ["Elegante", "Complejo", "Gastronómico"] },
  { id: "jardin-san-roque-negra-criolla", name: "San Roque Negra Criolla", winery: "Jardín Oculto", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Negra Criolla"], style: "Tinto", appearance: "Rojo-anaranjado pálido", nose: ["Cereza", "Ciruela", "Especias"], palate: ["Fruta roja", "Especiado", "Cierto agarre", "Sabroso"], character: ["Ligero a medio", "Especiado", "Rústico-elegante"], aromaFamilies: { Frutal: ["Cereza", "Ciruela"], Especiado: ["Especias"] }, palateAxes: { Cuerpo: "Ligero a medio", Astringencia: "Cierto agarre", Intensidad: "Media" } },
  { id: "jardin-los-membrillos", name: "Los Membrillos Negra Criolla", winery: "Jardín Oculto", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Negra Criolla"], style: "Tinto", appearance: "Rojo pálido", nose: ["Cereza roja", "Fresa"], palate: ["Frutal", "Texturado", "Membrillo"], character: ["Fino", "Jugoso", "Texturado", "Persistente"], aromaFamilies: { Frutal: ["Cereza roja", "Fresa", "Membrillo"] }, palateAxes: { Textura: "Texturado", Persistencia: "Persistente" } },
  { id: "alma-oculta-vischoquena", name: "Alma Oculta Vischoqueña", winery: "Hacienda La Compañía", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Vischoqueña"], style: "Tinto", appearance: "Rojo claro", nose: ["Uva fresca", "Notas fragantes", "Especias"], palate: ["Profundo", "Texturado", "Fino"], character: ["Fragante", "Elegante", "Especiado"] },
  { id: "yokich-imporena-centenarias", name: "Imporeña Cepas Centenarias", winery: "Yokich", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Imporeña"], style: "Tinto", appearance: "Variable según añada", nose: ["Fruta madura", "Carácter de uva"], palate: ["Jugoso", "Concentrado", "Amplio"], character: ["Con cuerpo", "Intenso", "Concentrado"], palateAxes: { Cuerpo: "Con cuerpo", Intensidad: "Alta", Textura: "Jugosa" } },
  { id: "yokich-cepas-misionera", name: "Cepas Misionera", winery: "Yokich", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Misionera", "Criolla"], style: "Tinto", appearance: "Rojo claro", nose: ["Cereza madura", "Fruta roja"], palate: ["Jugoso", "Texturado", "Cereza dulce", "Notas herbales-amargas"], character: ["Frutal", "Jugoso", "Equilibrado"], palateAxes: { Cuerpo: "Medio", Intensidad: "Media", Textura: "Jugosa" } },
  { id: "alma-oculta-naranjo", name: "Alma Oculta Naranjo", winery: "Hacienda La Compañía Baja", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Mezcla de viñedo antiguo"], style: "Naranjo", appearance: "Naranjo", nose: ["Perfil pendiente de ampliación"], palate: ["Extracción fenólica", "Estructura", "Textura"], character: ["Complejo", "Texturado"], process: "11 días de contacto con pieles" },
  { id: "jardin-moscatel-san-roque", name: "Moscatel de Alejandría San Roque", winery: "Jardín Oculto", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Moscatel de Alejandría"], style: "Blanco", appearance: "No documentada", nose: ["Lima dulce", "Piel de pomelo", "Durazno", "Ciruela ácida"], palate: ["Fresco", "Ligeramente reductivo"], character: ["Fresco", "Cítrico"], process: "Fermentación espontánea; una parte criada en huevo de concreto", fermentation: "Espontánea", aging: "Parcial", agingVessel: "Huevo de concreto", aromaFamilies: { Frutal: ["Lima", "Pomelo", "Durazno", "Ciruela"] }, palateAxes: { Acidez: "Fresca" } },
  { id: "san-francisco-horca-blanco", name: "Vino Blanco", winery: "San Francisco de la Horca", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Moscatel de Alejandría"], style: "Blanco", appearance: "No documentada", nose: ["Durazno meloso", "Piña"], palate: ["Lineal"], character: ["Frutal"], process: "Fermentación maloláctica y crianza en damajuana", malolactic: "Sí", aging: "Sí", agingVessel: "Damajuana", aromaFamilies: { Frutal: ["Durazno", "Piña"] } },
  { id: "cepa-oro-legado", name: "Legado de Rivera Real & Moscatel", winery: "Cepa de Oro", valley: "Valle de Cinti", department: "Chuquisaca", grapes: ["Real", "Moscatel"], style: "Blanco", appearance: "No documentada", nose: ["Ahumado", "Miel"], palate: ["Estructurado", "Complejo"], character: ["Blanco estructurado", "Complejo"], process: "Maceración con pieles", aromaFamilies: { Crianza: ["Ahumado"], Floral: ["Miel"] }, palateAxes: { Cuerpo: "Con cuerpo", Intensidad: "Alta" } },
  { id: "aranjuez-tannat", name: "Tannat", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Tannat"], style: "Tinto", appearance: "Rojo intenso con tonos púrpura", nose: ["Mora", "Arándano", "Frambuesa", "Roble"], palate: ["Taninos firmes", "Buena acidez", "Final largo"], character: ["Potente", "Estructurado", "Persistente"] },
  { id: "aranjuez-tannat-origen", name: "Tannat Origen", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Tannat"], style: "Tinto", appearance: "No documentada", nose: ["Mora negra", "Ciruela", "Arándanos maduros", "Vainilla", "Cacao"], palate: ["Perfil de boca pendiente de fuente"], character: ["Frutal", "Con notas de crianza"], aging: "Sí", agingVessel: "Roble" },
  { id: "aranjuez-cabernet", name: "Cabernet Sauvignon", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Cabernet Sauvignon"], style: "Tinto", appearance: "Rubí intenso", nose: ["Pimienta negra", "Pimiento", "Frutos rojos maduros", "Vainilla", "Cacao"], palate: ["Taninos sedosos", "Amplio", "Persistente"], character: ["Elegante", "Aterciopelado", "Estructurado"], palateAxes: { Taninos: "Sedosos", Cuerpo: "Amplio", Persistencia: "Persistente", Textura: "Aterciopelada" } },
  { id: "aranjuez-duo-blanco", name: "Dúo Blanco", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Sauvignon Blanc", "Chardonnay"], style: "Blanco", appearance: "Verde pálido y dorado", nose: ["Pomelo", "Durazno", "Piña", "Maracuyá"], palate: ["Acidez marcada", "Suave", "Redondo"], character: ["Fresco", "Tropical", "Buen cuerpo"] },
  { id: "aranjuez-terruno-tinto", name: "Terruño Tinto", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Blend tinto"], style: "Tinto", appearance: "Rubí con tonos violáceos", nose: ["Frutos rojos", "Vainilla", "Especias"], palate: ["Redondo", "Taninos moderados", "Cereza", "Ciruela"], character: ["Joven", "Frutal", "Redondo"], aromaFamilies: { Frutal: ["Frutos rojos", "Cereza", "Ciruela"], Especiado: ["Especias"], Crianza: ["Vainilla"] }, palateAxes: { Taninos: "Moderados", Cuerpo: "Medio", Textura: "Redonda" } },
  { id: "aranjuez-terruno-blanco", name: "Terruño Blanco", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Moscatel de Alejandría", "Blend"], style: "Blanco", appearance: "Dorado pálido con reflejos verdes", nose: ["Flores blancas"], palate: ["Cítrico", "Fresco", "Buena acidez"], character: ["Aromático", "Fresco", "Ligero"], aromaFamilies: { Floral: ["Flores blancas"], Frutal: ["Cítrico"] }, palateAxes: { Acidez: "Buena", Cuerpo: "Ligero" } },
  { id: "aranjuez-duo-tinto", name: "Dúo Tinto", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Tannat", "Merlot"], style: "Tinto", appearance: "Rubí intenso", nose: ["Frutos rojos", "Frutos negros", "Madera sutil"], palate: ["Estructura", "Suavidad"], character: ["Equilibrado", "Elegante", "Con cuerpo"], aromaFamilies: { Frutal: ["Frutos rojos", "Frutos negros"], Crianza: ["Madera sutil"] }, palateAxes: { Cuerpo: "Con cuerpo", Textura: "Suave" } },
  { id: "aranjuez-juan-cruz", name: "Juan Cruz", winery: "Aranjuez", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Tannat"], style: "Tinto", appearance: "Rojo violáceo profundo", nose: ["Mora", "Higo", "Dátiles", "Tabaco", "Vainilla", "Canela"], palate: ["Potente", "Taninos finos", "Sabores intensos"], character: ["Complejo", "Corpulento", "Largo"] },
  { id: "campos-trivarietal", name: "Trivarietal", winery: "Campos de Solana", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Cabernet Sauvignon", "Malbec", "Tannat"], style: "Tinto", appearance: "No documentada", nose: ["Mora", "Arándano", "Humo", "Tabaco", "Vainilla", "Chocolate"], palate: ["Carnoso", "Especiado", "Estructurado", "Persistente"], character: ["Complejo", "Corpulento", "Elegante"] },
  { id: "campos-cabernet", name: "Cabernet Sauvignon", winery: "Campos de Solana", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Cabernet Sauvignon"], style: "Tinto", appearance: "No documentada", nose: ["Cereza negra madura", "Lavanda", "Café", "Chocolate negro"], palate: ["Sedoso", "Taninos firmes", "Estructurado"], character: ["Profundo", "Persistente"], palateAxes: { Taninos: "Firmes", Textura: "Sedosa", Cuerpo: "Con cuerpo", Persistencia: "Persistente" } },
  { id: "campos-malbec", name: "Malbec", winery: "Campos de Solana", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Malbec"], style: "Tinto", appearance: "No documentada", nose: ["Frutos rojos", "Madera delicada"], palate: ["Suave", "Ciruela", "Cereza"], character: ["Frutal", "Elegante", "Equilibrado"] },
  { id: "campos-merlot", name: "Merlot", winery: "Campos de Solana", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Merlot"], style: "Tinto", appearance: "No documentada", nose: ["Mora", "Cassis", "Grosella negra", "Cereza"], palate: ["Taninos nobles", "Equilibrado", "Final largo"], character: ["Aterciopelado", "Amable", "Persistente"], palateAxes: { Taninos: "Nobles", Textura: "Aterciopelada", Persistencia: "Larga" } },
  { id: "concepcion-syrah", name: "Cepas de Altura Syrah", winery: "La Concepción", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Syrah"], style: "Tinto", appearance: "No documentada", nose: ["Cassis", "Frutos negros", "Ciruela", "Clavo", "Humo"], palate: ["Amplio", "Suave", "Armónico", "Buena acidez"], character: ["Con cuerpo", "Opulento", "Especiado"] },
  { id: "concepcion-cabernet", name: "Cepas de Altura Cabernet Sauvignon", winery: "La Concepción", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Cabernet Sauvignon"], style: "Tinto", appearance: "No documentada", nose: ["Cereza negra", "Mora", "Pimiento verde", "Tabaco"], palate: ["Fruto negro", "Humo", "Final largo"], character: ["Con cuerpo", "Seco", "Estructurado", "Persistente"] },
  { id: "el-potro-moscatel", name: "Moscatel", winery: "Bodega El Potro", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Moscatel de Alejandría"], style: "Blanco", appearance: "No documentada", nose: ["Pétalos de rosa", "Lichi", "Durazno blanco"], palate: ["Damasco", "Manzana blanca", "Pomelo"], character: ["Muy aromático", "Floral", "Frutal", "Semidulce"] },
  { id: "el-potro-syrah", name: "Syrah", winery: "Bodega El Potro", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Syrah"], style: "Tinto", appearance: "No documentada", nose: ["Grosella negra", "Ciruela", "Especias"], palate: ["Fruta negra", "Taninos suaves", "Gran frescura"], character: ["Especiado", "Frutal", "Equilibrado"] },
  { id: "el-potro-malbec", name: "Malbec", winery: "Bodega El Potro", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Malbec"], style: "Tinto", appearance: "No documentada", nose: ["Ciruela", "Vainilla", "Humo", "Tabaco"], palate: ["Carnoso", "Taninos maduros", "Persistente"], character: ["Carnoso", "Complejo", "Largo"] },
  { id: "altosama-rose", name: "Altosama Rosé", winery: "Altosama", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Tempranillo", "Pinot Meunier", "Marselan"], style: "Espumante", appearance: "Rosado", nose: ["Fresa", "Cereza", "Ciruela", "Cítricos", "Flores"], palate: ["Fresco", "Frutal", "Vivaz"], character: ["Frutal", "Floral", "Refrescante"], process: "Método Charmat" },
  { id: "altosama-demi-sec", name: "Altosama Demi Sec", winery: "Altosama", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Chardonnay", "Pinot Meunier", "Xarel·lo", "Moscatel"], style: "Espumante", appearance: "No documentada", nose: ["Pomelo", "Piña", "Limón", "Jazmín"], palate: ["Burbujas finas", "Equilibrio entre acidez y dulzor"], character: ["Fresco", "Floral", "Tropical", "Elegante"], process: "Método Charmat", aromaFamilies: { Frutal: ["Pomelo", "Piña", "Limón"], Floral: ["Jazmín"] }, palateAxes: { Dulzor: "Demi-sec", Acidez: "Equilibrada", Textura: "Burbujas finas" } },
  { id: "kohlberg-ugni-blanc", name: "Ugni Blanc", winery: "Kohlberg", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Ugni Blanc"], style: "Blanco", appearance: "Amarillo pálido brillante", nose: ["Perfil mineral", "Fruta blanca fresca"], palate: ["Seco", "Mineral", "Fresco", "Cremoso"], character: ["Fresco", "Cremoso", "Equilibrado"], palateAxes: { Dulzor: "Seco", Acidez: "Fresca", Cuerpo: "Medio", Textura: "Cremosa" } },
  { id: "jardin-lado-b-tannat-nouveau", name: "Lado B Tannat Nouveau", winery: "Jardín Oculto", valley: "Valle Central de Tarija", department: "Tarija", grapes: ["Tannat"], style: "Tinto", appearance: "Rojo brillante", nose: ["Frutos del bosque", "Cereza negra"], palate: ["Jugoso", "Brillante", "Fresco", "Buena acidez"], character: ["Ligero a medio", "Frutal", "Fresco", "Menos pesado"], palateAxes: { Acidez: "Buena", Taninos: "Suaves", Cuerpo: "Ligero a medio", Textura: "Jugosa" } },
];
